version: 2.1
jobs:
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
              # You can get this ID in the section where you registered the SSH Key
              fingerprints: ["bd:52:40:9a:15:27:87:5d:2a:82:02:15:15:1a:0a:f3"] 
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory.txt main.yml


#add workload
workflows:
  myWorkflow:
    jobs:
      - configure_infrastructure